# Generated by Django 4.0.4 on 2022-05-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.product')),
                ('screen_technology', models.CharField(max_length=65, verbose_name='Screen technology')),
                ('operating_system', models.CharField(max_length=65, verbose_name='Operating sistem')),
                ('os_version', models.CharField(max_length=65, verbose_name='OS version')),
                ('screen_size', models.FloatField(verbose_name='Screen Size')),
                ('screen_resolution', models.CharField(max_length=65, verbose_name='Screen resolution')),
                ('ram', models.PositiveIntegerField()),
                ('built_in_memory', models.PositiveIntegerField()),
                ('cpu', models.CharField(max_length=255, verbose_name='CPU')),
                ('num_of_cores', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mainapp.product',),
        ),
        migrations.RemoveField(
            model_name='smartspeaker',
            name='market_launch_date',
        ),
        migrations.RemoveField(
            model_name='smartspeaker',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='market_launch_date',
            field=models.CharField(default=1, max_length=15, verbose_name='Market launch date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=1, max_length=56, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
