# Generated by Django 4.0.4 on 2022-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_productimagesset_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagesset',
            name='main_img',
            field=models.BooleanField(blank=True, null=True, verbose_name='Main image'),
        ),
    ]
