# Generated by Django 4.0.4 on 2022-05-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_product_image_productimagesset_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimagesset',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productimagesset', verbose_name='Product image'),
            preserve_default=False,
        ),
    ]
