# Generated by Django 4.0.4 on 2022-06-13 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Review Creator'),
        ),
        migrations.CreateModel(
            name='ProductReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=700, verbose_name='Reply review text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation reply')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_reply', to='mainapp.productreview', verbose_name='Reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews_reply', to=settings.AUTH_USER_MODEL, verbose_name='Reply Creator')),
            ],
        ),
    ]
