# Generated by Django 4.0.4 on 2022-06-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_productreview_user_productreviewreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviewreply',
            old_name='product',
            new_name='review',
        ),
    ]
