# Generated by Django 4.0.4 on 2022-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='', verbose_name='Profile Photo'),
        ),
    ]
